const BeefData = [
    {
        id: 1,
        Image: "",
        Title: "Chuck",
        Description: "Beef chuck comes from the forequarter. Consisting of parts of the neck, shoulder blade, and upper arm, beef chuck produces tough but very flavorful cuts of meat.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 2,
        Image: "",
        Title: "Rib",
        Description: "Made from the top part of the center section of rib—specifically the sixth through the twelfth ribs— the beef rib primal cut is used for the traditional standing rib roast (also called prime rib).",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 3,
        Image: "",
        Title: "Short Loin",
        Description: `"Moving on to the beef primal cuts from the hindquarter, or back of the animal, the short loin is where we find the most desirable cuts of meat. These include T-bone and porterhouse steaks, as well as the strip loin or strip steak.."`,
        Category: "",
        Price: "$00.00",
    },
    {
        id: 4,
        Image: "",
        Title: "Plate",
        Description: `"Also called the short plate (or {"long plate"} depending on where it's separated from the rib primal above it), the beef plate primal includes the short ribs."`,
        Category: "",
        Price: "$00.00",
    },
    {
        id: 5,
        Image: "",
        Title: "Tenderloin",
        Description: "The most tender cut of beef is the beef tenderloin and it is found within the loin. This is where we get filet mignon, which is made from the very tip of the pointy end of the tenderloin.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 6,
        Image: "",
        Title: "Round",
        Description: "The beef round primal cut basically consists of the back leg of the steer. Muscles from the round are fairly lean, but they're also tough because the leg and rump get a lot of exercise.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 7,
        Image: "",
        Title: "Brisket",
        Description: "Beef brisket is one of the most flavorful cuts of meat, although it is tough and needs to be cooked in just the right way.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 8,
        Image: "",
        Title: "Sirloin",
        Description: "Beef sirloin is another large section of the carcass that runs from the 13th rib all the way back to the hip bone and from the backbone clear down to the flank (or belly).",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 9,
        Image: "",
        Title: "Flank",
        Description: "Beef flank can be cooked on the grill. Since it has tough muscle fibers, it can get even tougher if it's overcooked, so be careful.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 10,
        Image: "",
        Title: "Shank",
        Description: "The beef shank is the leg of the animal's thigh. Each side of beef has two shanks, one in the forequarter and one in the hindquarter. It is extremely tough and full of connective tissue.",
        Category: "",
        Price: "$00.00",
    },
]

export default BeefData