const Chicken = [
    {
        id: 1,
        Image: "",
        Title: "Leg",
        Description: "One whole chicken. Defeathered and packaged",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 2,
        Image: "",
        Title: "CBreast",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 3,
        Image: "",
        Title: "Wing",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 4,
        Image: "",
        Title: "Thigh",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 5,
        Image: "",
        Title: "Drumstick",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 6,
        Image: "",
        Title: "Back",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 7,
        Image: "",
        Title: "Foot",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
]

export default Chicken