const Chicken = [
    {
        id: 1,
        Image: "",
        Title: "Whole Chicken",
        Description: "Whole chicken which consists of breast, thigh, wings, neck and back. It may contain one liver, one stomach and one heart. It is ideal for oven or even for soup and stews, if cut in parts.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 2,
        Image: "",
        Title: "Leg",
        Description: "Each chicken has two legs which in turn are divided into the Thigh and Drumstick via a clavicle. The leg includes bone and skin. Its flesh is characteristic pink and is more juicy and fatty than the chest.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 3,
        Image: "",
        Title: "Breast",
        Description: "The whole chicken breast with bones and skin. The bone has a characteristic boat keel shape. The meat is white and low in fat.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 4,
        Image: "",
        Title: "Wing",
        Description: "The most disputable chicken part. While for some is not their favorite part, others just can’t have enough. It clearly has the most dedicated fans that will not miss a chance to taste it breaded, barbequed or cooked in any way.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 4,
        Image: "",
        Title: "Thigh",
        Description: "The leg fillet is the thigh without bone and skin. It is the most juicy piece of chicken and recommended for every use.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 5,
        Image: "",
        Title: "Drumstick",
        Description: "The drumstick has the look of a drum baguette. It’s the children’s favorite part, while it is better enjoyed eating by hand. Recommended for frying, oven baking and cooked meals.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 6,
        Image: "",
        Title: "Neck",
        Description: "It is a fine delicacy. Because of its content in fat is ideal for gravies, soups and stews as it offers extra flavor.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 7,
        Image: "",
        Title: "Back",
        Description: "It is a fine delicacy. Because of its content in fat is ideal for gravies, soups and stews as it offers extra flavor.",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 8,
        Image: "",
        Title: "Foot",
        Description: "It is a fine delicacy. Because of its content in fat is ideal for gravies, soups and stews as it offers extra flavor.",
        Category: "",
        Price: "$00.00",
    },
]

export default Chicken