const MuttonData = [
  {
    id: 1,
    Image: "",
    Title: "Diced Leg",
    Description: "Lean cuts from the leg, diced by hand.",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 2,
    Image: "",
    Title: "Diced Mutton Shoulder",
    Description: "Marbled cuts from the shoulder, diced by hand",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 3,
    Image: "",
    Title: "Ground Mutton",
    Description: "Made from leaner shoulder cuts, gristle removed.",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 4,
    Image: "",
    Title: "Mutton Breast",
    Description: "The whole breast of mutton, on the bone.",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 5,
    Image: "",
    Title: "Mottun Chops",
    Description: "A versatile cut taken from the mutton loin.",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 6,
    Image: "",
    Title: "Motton Leg",
    Description: "The most popular mutton roasting joint.",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 7,
    Image: "",
    Title: "Mutton Loin",
    Description: "Bone-in sirloin and fillet of mutton.",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 8,
    Image: "",
    Title: "Mutton Scrag",
    Description: "Mutton neck, on the bone.",
    Category: "",
    Price: "$00.00",
  },
  {
    id: 9,
    Image: "",
    Title: "Mutton Shoulder",
    Description: "A fantastic, flavoursome joint for roasting.",
    Category: "",
    Price: "$00.00",
  },
];

export default MuttonData;
