const PorkData = [
    {
        id: 1,
        Image: "",
        Title: "Becon",
        Description: "One whole chicken. Defeathered and packaged",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 2,
        Image: "",
        Title: "Ground Pork",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 3,
        Image: "",
        Title: "Ham",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 4,
        Image: "",
        Title: "Pork Belly",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 5,
        Image: "",
        Title: "Pork Chops",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 6,
        Image: "",
        Title: "Pork Loin Roast",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 7,
        Image: "",
        Title: "Pork Rib Roast",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 8,
        Image: "",
        Title: "Pork Ribs",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 9,
        Image: "",
        Title: "Pork Shoulder",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 10,
        Image: "",
        Title: "Pork Steak",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 11,
        Image: "",
        Title: "Pork Tenderloin",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
    {
        id: 12,
        Image: "",
        Title: "Sausage",
        Description: "",
        Category: "",
        Price: "$00.00",
    },
]

export default PorkData